import { useCallback } from 'react';
import { useNavigate as useNavigateOrigin } from 'react-router-dom';

export enum RouteTypes {
    BoostScreen = 'BoostScreen',
    WelcomeScreen = 'WelcomeScreen',
    MainScreen = 'MainScreen',
    AppTabScrren = 'AppTabScrren',
    SettingsTabScreen = 'SettingsTabScreen',
    CreateHDWalletScreen = 'CreateHDWalletScreen',
    CreateAccountScreen = 'CreateAccountScreen',
    CreatePasswordScreen = 'CreatePasswordScreen',
    UnlockScreen = 'UnlockScreen',
    SwitchAccountScreen = 'SwitchAccountScreen',
    ReceiveScreen = 'ReceiveScreen',
    ReceiveSelectScreen = 'ReceiveSelectScreen',
    TxConfirmScreen = 'TxConfirmScreen',
    TxOpnetConfirmScreen = 'TxOpnetConfirmScreen',
    TxSuccessScreen = 'TxSuccessScreen',
    TxFailScreen = 'TxFailScreen',
    NetworkTypeScreen = 'NetworkTypeScreen',
    ChangePasswordScreen = 'ChangePasswordScreen',
    ExportMnemonicsScreen = 'ExportMnemonicsScreen',
    ExportPrivateKeyScreen = 'ExportPrivateKeyScreen',
    AdvancedScreen = 'AdvancedScreen',
    ApprovalScreen = 'ApprovalScreen',
    ConnectedSitesScreen = 'ConnectedSitesScreen',
    SwitchKeyringScreen = 'SwitchKeyringScreen',
    AddKeyringScreen = 'AddKeyringScreen',
    EditWalletNameScreen = 'EditWalletNameScreen',
    CreateSimpleWalletScreen = 'CreateSimpleWalletScreen',
    CreateKeystoneWalletScreen = 'CreateKeystoneWalletScreen',
    UpgradeNoticeScreen = 'UpgradeNoticeScreen',
    AddressTypeScreen = 'AddressTypeScreen',
    EditAccountNameScreen = 'EditAccountNameScreen',
    UnavailableUtxoScreen = 'UnavailableUtxoScreen',
    OpNetTokenScreen = 'OpNetTokenScreen',
    SendOpNetScreen = 'SendOpNetScreen',
    TxCreateScreen = 'TxCreateScreen',
    DeployContract = 'DeployContract',
    Mint = 'Mint',
    ImportSelectionScreen = 'ImportSelectionScreen',
    ImportNFTScreen = 'ImportNFTScreen',
    NFTTabScreen = 'NFTTabScreen',
    NFTSendScreen = 'NFTSendScreen',
    ImportTokenScreen = 'ImportTokenScreen',
    QuantumMigrationScreen = 'QuantumMigrationScreen',
    DuplicationResolutionScreen = 'DuplicationResolutionScreen',
    HistoryScreen = 'HistoryScreen',
    TransactionDetailScreen = 'TransactionDetailScreen',
    OpnetBrowserScreen = 'OpnetBrowserScreen',
    BtcDomainScreen = 'BtcDomainScreen',
    AddressRotationScreen = 'AddressRotationScreen',
    RotationHistoryScreen = 'RotationHistoryScreen',
    ConsolidationScreen = 'ConsolidationScreen',
    ColdStorageWithdrawScreen = 'ColdStorageWithdrawScreen',
    UserExperienceModeScreen = 'UserExperienceModeScreen',
    DisplaySettingsScreen = 'DisplaySettingsScreen',
    LegacyVaultHomeScreen = 'LegacyVaultHomeScreen',
    LegacyVaultCreateScreen = 'LegacyVaultCreateScreen',
    LegacyVaultReviewScreen = 'LegacyVaultReviewScreen',
    LegacyVaultStatusScreen = 'LegacyVaultStatusScreen',
    LegacyVaultClaimScreen = 'LegacyVaultClaimScreen',
    RockPaperScissorsHomeScreen = 'RockPaperScissorsHomeScreen'
}

export const routePaths: Record<RouteTypes, string> = {
    [RouteTypes.BoostScreen]: '/',
    [RouteTypes.WelcomeScreen]: '/welcome',
    [RouteTypes.MainScreen]: '/main',
    [RouteTypes.AppTabScrren]: '/app',
    [RouteTypes.SettingsTabScreen]: '/settings',
    [RouteTypes.CreateHDWalletScreen]: '/account/create-hd-wallet',
    [RouteTypes.CreateAccountScreen]: '/account/create',
    [RouteTypes.CreatePasswordScreen]: '/account/create-password',
    [RouteTypes.UnlockScreen]: '/account/unlock',
    [RouteTypes.SwitchAccountScreen]: '/account/switch-account',
    [RouteTypes.ReceiveScreen]: '/wallet/receive',
    [RouteTypes.ReceiveSelectScreen]: '/wallet/receive-select',
    [RouteTypes.TxConfirmScreen]: '/wallet/tx/confirm',
    [RouteTypes.TxOpnetConfirmScreen]: '/wallet/tx/confirm-opnet',
    [RouteTypes.TxSuccessScreen]: '/wallet/tx/success',
    [RouteTypes.TxFailScreen]: '/wallet/tx/fail',
    [RouteTypes.NetworkTypeScreen]: '/settings/network-type',
    [RouteTypes.ChangePasswordScreen]: '/settings/password',
    [RouteTypes.ExportMnemonicsScreen]: '/settings/export-mnemonics',
    [RouteTypes.ExportPrivateKeyScreen]: '/settings/export-privatekey',
    [RouteTypes.AdvancedScreen]: '/settings/advanced',
    [RouteTypes.ApprovalScreen]: '/approval',
    [RouteTypes.ConnectedSitesScreen]: '/connected-sites',
    [RouteTypes.SwitchKeyringScreen]: '/account/switch-keyring',
    [RouteTypes.AddKeyringScreen]: '/account/add-keyring',
    [RouteTypes.EditWalletNameScreen]: '/settings/edit-wallet-name',
    [RouteTypes.CreateSimpleWalletScreen]: '/account/create-simple-wallet',
    [RouteTypes.CreateKeystoneWalletScreen]: '/account/create-keystone-wallet',
    [RouteTypes.UpgradeNoticeScreen]: '/settings/upgrade-notice',
    [RouteTypes.AddressTypeScreen]: '/settings/address-type',
    [RouteTypes.EditAccountNameScreen]: '/settings/edit-account-name',
    [RouteTypes.UnavailableUtxoScreen]: '/wallet/unavailable-utxo',
    [RouteTypes.OpNetTokenScreen]: '/opnet/token',
    [RouteTypes.SendOpNetScreen]: '/opnet/send-opnet',
    [RouteTypes.TxCreateScreen]: '/wallet/tx/create',
    [RouteTypes.DeployContract]: '/opnet/deploy-contract',
    [RouteTypes.Mint]: '/opnet/mint',
    [RouteTypes.ImportSelectionScreen]: '/import-selection',
    [RouteTypes.ImportNFTScreen]: '/import-nft',
    [RouteTypes.NFTTabScreen]: '/nft',
    [RouteTypes.NFTSendScreen]: '/nft-send',
    [RouteTypes.ImportTokenScreen]: '/import-token',
    [RouteTypes.QuantumMigrationScreen]: '/settings/quantum-migration',
    [RouteTypes.DuplicationResolutionScreen]: '/settings/duplication-resolution',
    [RouteTypes.HistoryScreen]: '/history',
    [RouteTypes.TransactionDetailScreen]: '/history/transaction',
    [RouteTypes.OpnetBrowserScreen]: '/settings/opnet-browser',
    [RouteTypes.BtcDomainScreen]: '/domain',
    [RouteTypes.AddressRotationScreen]: '/settings/address-rotation',
    [RouteTypes.RotationHistoryScreen]: '/settings/rotation-history',
    [RouteTypes.ConsolidationScreen]: '/settings/consolidation',
    [RouteTypes.ColdStorageWithdrawScreen]: '/settings/cold-storage-withdraw',
    [RouteTypes.UserExperienceModeScreen]: '/settings/experience-mode',
    [RouteTypes.DisplaySettingsScreen]: '/settings/display',
    [RouteTypes.LegacyVaultHomeScreen]: '/legacy-vault',
    [RouteTypes.LegacyVaultCreateScreen]: '/legacy-vault/create',
    [RouteTypes.LegacyVaultReviewScreen]: '/legacy-vault/review',
    [RouteTypes.LegacyVaultStatusScreen]: '/legacy-vault/status',
    [RouteTypes.LegacyVaultClaimScreen]: '/legacy-vault/claim',
    [RouteTypes.RockPaperScissorsHomeScreen]: '/rock-paper-scissors'
};

export type UseNavigate<T extends RouteTypes> = (routKey: T, state?: unknown) => void;

export function useNavigate<T extends RouteTypes>(): UseNavigate<T> {
    const navigate = useNavigateOrigin();

    return useCallback(
        (routKey: T, state?: unknown) => {
            navigate(routePaths[routKey], { state });
        },
        [navigate]
    ) as UseNavigate<T>;
}
